name: battle-heroes # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Battle of Heroes
summary: Build strategies and defeat opponents.
description: Assemble your team of heroes with unique powers and battle others in strategic, action-packed matches.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  battle-heroes:
    command: bin/battle-heroes-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  battle-heroes:
    plugin: dump
    source: .
    organize:
      battle-heroes-bin: bin/
